//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ders51_Ust_Alt_Kategori.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Araba
    {
        public int categoryID { get; set; }
        public string Adi { get; set; }
        public Nullable<int> UstMenuID { get; set; }
    }
}
